name: Deploy Cognite Function
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ./
        env: 
          DELETE_PR: true
        with:
          cdf_project: andershaf
          cdf_base_url: https://api.cognitedata.com
          cdf_credentials: ${{ secrets.COGNITE_API_KEY }}
          handler_path: example/handler.py
