name: Delete Cognite Function
on:
  pull_request:
    # types: closed
jobs:
  deploy:
    name: Delete PR function
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: ./
        env: 
          DELETE_PR: true
        with:
          cdf_project: andershaf
          cdf_base_url: https://api.cognitedata.com
          cdf_credentials: ${{ secrets.COGNITE_API_KEY }}
          handler_path: example/handler.py
